services:
  - type: web
    name: beaches-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: "https://your-frontend.vercel.app"
